// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// FM
List FM(List data_, IntegerVector normalize, List fm_controls, List solver_controls, List track_controls, List model_list);
RcppExport SEXP FMwR_FM(SEXP data_SEXP, SEXP normalizeSEXP, SEXP fm_controlsSEXP, SEXP solver_controlsSEXP, SEXP track_controlsSEXP, SEXP model_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type data_(data_SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< List >::type fm_controls(fm_controlsSEXP);
    Rcpp::traits::input_parameter< List >::type solver_controls(solver_controlsSEXP);
    Rcpp::traits::input_parameter< List >::type track_controls(track_controlsSEXP);
    Rcpp::traits::input_parameter< List >::type model_list(model_listSEXP);
    __result = Rcpp::wrap(FM(data_, normalize, fm_controls, solver_controls, track_controls, model_list));
    return __result;
END_RCPP
}
// FMPredict
NumericVector FMPredict(List newdata, bool normalize, List model_list, int max_threads);
RcppExport SEXP FMwR_FMPredict(SEXP newdataSEXP, SEXP normalizeSEXP, SEXP model_listSEXP, SEXP max_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type newdata(newdataSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< List >::type model_list(model_listSEXP);
    Rcpp::traits::input_parameter< int >::type max_threads(max_threadsSEXP);
    __result = Rcpp::wrap(FMPredict(newdata, normalize, model_list, max_threads));
    return __result;
END_RCPP
}
// FMTrack
NumericVector FMTrack(List newdata, List model_list, bool normalize, String type, int max_threads);
RcppExport SEXP FMwR_FMTrack(SEXP newdataSEXP, SEXP model_listSEXP, SEXP normalizeSEXP, SEXP typeSEXP, SEXP max_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type newdata(newdataSEXP);
    Rcpp::traits::input_parameter< List >::type model_list(model_listSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type max_threads(max_threadsSEXP);
    __result = Rcpp::wrap(FMTrack(newdata, model_list, normalize, type, max_threads));
    return __result;
END_RCPP
}
// normalize
List normalize(NumericMatrix matrix, const int nthreads);
RcppExport SEXP FMwR_normalize(SEXP matrixSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    __result = Rcpp::wrap(normalize(matrix, nthreads));
    return __result;
END_RCPP
}
// normalize1
void normalize1(NumericMatrix matrix, List scales, const int nthreads);
RcppExport SEXP FMwR_normalize1(SEXP matrixSEXP, SEXP scalesSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< List >::type scales(scalesSEXP);
    Rcpp::traits::input_parameter< const int >::type nthreads(nthreadsSEXP);
    normalize1(matrix, scales, nthreads);
    return R_NilValue;
END_RCPP
}
// NApredict
NumericVector NApredict(NumericVector pred, IntegerVector nas);
RcppExport SEXP FMwR_NApredict(SEXP predSEXP, SEXP nasSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nas(nasSEXP);
    __result = Rcpp::wrap(NApredict(pred, nas));
    return __result;
END_RCPP
}
// transpose
List transpose(List sparse_matrix);
RcppExport SEXP FMwR_transpose(SEXP sparse_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type sparse_matrix(sparse_matrixSEXP);
    __result = Rcpp::wrap(transpose(sparse_matrix));
    return __result;
END_RCPP
}
