# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FM <- function(data_, target, fm_controls, solver_controls, validation_controls) {
    .Call('FMwR_FM', PACKAGE = 'FMwR', data_, target, fm_controls, solver_controls, validation_controls)
}

normalize <- function(matrix, nthreads = 1L) {
    .Call('FMwR_normalize', PACKAGE = 'FMwR', matrix, nthreads)
}

normalize1 <- function(matrix, scales, nthreads = 1L) {
    invisible(.Call('FMwR_normalize1', PACKAGE = 'FMwR', matrix, scales, nthreads))
}

